package mptrafficserver

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestParsePluginConfig(t *testing.T) {
	stat := make(map[string]interface{})
	parseVars(&parseVarsStub, &stat)

	assert.EqualValues(t, stat["cache_hits"], 6565601)
	assert.EqualValues(t, stat["cache_misses"], 75019942)
	assert.EqualValues(t, stat["http_2xx"], 70643724)
	assert.EqualValues(t, stat["http_3xx"], 10322721)
	assert.EqualValues(t, stat["http_4xx"], 499852)
	assert.EqualValues(t, stat["http_5xx"], 164237)
	assert.EqualValues(t, stat["conn_server"], 90)
	assert.EqualValues(t, stat["conn_client"], 2)
}

var parseVarsStub = `
proxy.node.num_processes 0
proxy.node.hostname_FQ examplehost
proxy.node.hostname examplehost
proxy.node.restarts.manager.start_time 1425810282
proxy.node.restarts.proxy.start_time 1425810283
proxy.node.restarts.proxy.cache_ready_time 1425810284
proxy.node.restarts.proxy.stop_time 0
proxy.node.restarts.proxy.restart_count 1
proxy.node.bandwidth_hit_ratio 0.125318
proxy.node.bandwidth_hit_ratio_int_pct 140406400
proxy.node.hostdb.hit_ratio 0.448454
proxy.node.hostdb.hit_ratio_int_pct 502449216
proxy.node.proxy_running 1
proxy.node.cache.percent_free 0.001564
proxy.node.cache_hit_ratio 0.080475
proxy.node.cache_hit_ratio_int_pct 90164528
proxy.node.cache_hit_ratio_avg_10s_int_pct 65906084
proxy.node.cache_hit_mem_ratio 0.000000
proxy.node.cache_hit_mem_ratio_int_pct 0
proxy.node.cache_hit_mem_ratio_avg_10s_int_pct 0
proxy.node.bandwidth_hit_ratio_avg_10s_int_pct 272654112
proxy.node.bandwidth_hit_ratio_avg_10s 0.243354
proxy.node.http.cache_hit_fresh_avg_10s 1.000000
proxy.node.http.cache_hit_mem_fresh_avg_10s 0.000000
proxy.node.http.cache_hit_revalidated_avg_10s 3.000000
proxy.node.http.cache_hit_ims_avg_10s 0.000000
proxy.node.http.cache_hit_stale_served_avg_10s 0.000000
proxy.node.http.cache_miss_cold_avg_10s 53.000000
proxy.node.http.cache_miss_changed_avg_10s 11.000000
proxy.node.http.cache_miss_not_cacheable_avg_10s 0.000000
proxy.node.http.cache_miss_client_no_cache_avg_10s 0.000000
proxy.node.http.cache_miss_ims_avg_10s 0.000000
proxy.node.http.cache_read_error_avg_10s 0.000000
proxy.node.cache_total_hits_avg_10s 4.000000
proxy.node.cache_total_hits_mem_avg_10s 0.000000
proxy.node.cache_total_misses_avg_10s 64.000000
proxy.node.cache_hit_ratio_avg_10s 0.058824
proxy.node.cache_hit_mem_ratio_avg_10s 0.000000
proxy.node.hostdb.total_lookups_avg_10s 75.000000
proxy.node.hostdb.total_hits_avg_10s 32.000000
proxy.node.hostdb.hit_ratio_avg_10s 0.426667
proxy.node.http.transaction_counts_avg_10s.hit_fresh 1.000000
proxy.node.http.transaction_counts_avg_10s.hit_revalidated 3.000000
proxy.node.http.transaction_counts_avg_10s.miss_cold 53.000000
proxy.node.http.transaction_counts_avg_10s.miss_not_cacheable 6.000000
proxy.node.http.transaction_counts_avg_10s.miss_changed 11.000000
proxy.node.http.transaction_counts_avg_10s.miss_client_no_cache 0.000000
proxy.node.http.transaction_counts_avg_10s.errors.connect_failed 0.000000
proxy.node.http.transaction_counts_avg_10s.errors.aborts 0.000000
proxy.node.http.transaction_counts_avg_10s.errors.possible_aborts 0.000000
proxy.node.http.transaction_counts_avg_10s.errors.pre_accept_hangups 0.000000
proxy.node.http.transaction_counts_avg_10s.errors.early_hangups 0.000000
proxy.node.http.transaction_counts_avg_10s.errors.empty_hangups 0.000000
proxy.node.http.transaction_counts_avg_10s.errors.other 0.000000
proxy.node.http.transaction_counts_avg_10s.other.unclassified 0.000000
proxy.node.http.transaction_frac_avg_10s.hit_fresh 0.013514
proxy.node.http.transaction_frac_avg_10s.hit_revalidated 0.040541
proxy.node.http.transaction_frac_avg_10s.miss_cold 0.716216
proxy.node.http.transaction_frac_avg_10s.miss_not_cacheable 0.081081
proxy.node.http.transaction_frac_avg_10s.miss_changed 0.148649
proxy.node.http.transaction_frac_avg_10s.miss_client_no_cache 0.000000
proxy.node.http.transaction_frac_avg_10s.errors.connect_failed 0.000000
proxy.node.http.transaction_frac_avg_10s.errors.aborts 0.000000
proxy.node.http.transaction_frac_avg_10s.errors.possible_aborts 0.000000
proxy.node.http.transaction_frac_avg_10s.errors.pre_accept_hangups 0.000000
proxy.node.http.transaction_frac_avg_10s.errors.early_hangups 0.000000
proxy.node.http.transaction_frac_avg_10s.errors.empty_hangups 0.000000
proxy.node.http.transaction_frac_avg_10s.errors.other 0.000000
proxy.node.http.transaction_frac_avg_10s.other.unclassified 0.000000
proxy.node.http.transaction_frac_avg_10s.hit_fresh_int_pct 15140588
proxy.node.http.transaction_frac_avg_10s.hit_revalidated_int_pct 45421760
proxy.node.http.transaction_frac_avg_10s.miss_cold_int_pct 802451136
proxy.node.http.transaction_frac_avg_10s.miss_not_cacheable_int_pct 90843520
proxy.node.http.transaction_frac_avg_10s.miss_changed_int_pct 166546464
proxy.node.http.transaction_frac_avg_10s.miss_client_no_cache_int_pct 0
proxy.node.http.transaction_frac_avg_10s.errors.connect_failed_int_pct 0
proxy.node.http.transaction_frac_avg_10s.errors.aborts_int_pct 0
proxy.node.http.transaction_frac_avg_10s.errors.possible_aborts_int_pct 0
proxy.node.http.transaction_frac_avg_10s.errors.pre_accept_hangups_int_pct 0
proxy.node.http.transaction_frac_avg_10s.errors.early_hangups_int_pct 0
proxy.node.http.transaction_frac_avg_10s.errors.empty_hangups_int_pct 0
proxy.node.http.transaction_frac_avg_10s.errors.other_int_pct 0
proxy.node.http.transaction_frac_avg_10s.other.unclassified_int_pct 0
proxy.node.http.transaction_msec_avg_10s.hit_fresh 0
proxy.node.http.transaction_msec_avg_10s.hit_revalidated 931
proxy.node.http.transaction_msec_avg_10s.miss_cold 984
proxy.node.http.transaction_msec_avg_10s.miss_not_cacheable 969
proxy.node.http.transaction_msec_avg_10s.miss_changed 968
proxy.node.http.transaction_msec_avg_10s.miss_client_no_cache 0
proxy.node.http.transaction_msec_avg_10s.errors.connect_failed 0
proxy.node.http.transaction_msec_avg_10s.errors.aborts 0
proxy.node.http.transaction_msec_avg_10s.errors.possible_aborts 0
proxy.node.http.transaction_msec_avg_10s.errors.pre_accept_hangups 0
proxy.node.http.transaction_msec_avg_10s.errors.early_hangups 0
proxy.node.http.transaction_msec_avg_10s.errors.empty_hangups 0
proxy.node.http.transaction_msec_avg_10s.errors.other 0
proxy.node.http.transaction_msec_avg_10s.other.unclassified 0
proxy.node.http.throughput 626565
proxy.node.http.user_agent_xacts_per_second 7.497867
proxy.node.http.user_agent_current_connections_count 2
proxy.node.http.user_agent_total_request_bytes 18152137443
proxy.node.http.user_agent_total_response_bytes 6525938625728
proxy.node.http.user_agents_total_transactions_count 88198085
proxy.node.http.user_agents_total_documents_served 88198085
proxy.node.http.origin_server_current_connections_count 90
proxy.node.http.origin_server_total_request_bytes 21298106387
proxy.node.http.origin_server_total_response_bytes 5702702216882
proxy.node.http.parent_proxy_total_request_bytes 0
proxy.node.http.parent_proxy_total_response_bytes 0
proxy.node.http.origin_server_total_transactions_count 86509710
proxy.node.http.cache_current_connections_count 2
proxy.node.http.current_parent_proxy_connections 0
proxy.node.cache.contents.num_docs 0
proxy.node.cache.bytes_total 5361975296
proxy.node.cache.bytes_total_mb 5113
proxy.node.cache.bytes_free 8388608
proxy.node.cache.bytes_free_mb 8
proxy.node.cache.percent_free_int_pct 1752829
proxy.node.cache_total_hits 6565601
proxy.node.cache_total_hits_mem 0
proxy.node.cache_total_misses 75019942
proxy.node.current_cache_connections 2
proxy.node.dns.lookups_per_second 73.978951
proxy.node.dns.lookup_avg_time_ms 0
proxy.node.dns.total_dns_lookups 1175434674
proxy.node.hostdb.total_lookups 86545131
proxy.node.hostdb.total_hits 38811492
proxy.node.cluster.nodes 1
proxy.node.client_throughput_out 5.012520
proxy.node.client_throughput_out_kbit 5758614016
proxy.node.current_client_connections 2
proxy.node.current_server_connections 90
proxy.node.user_agent_total_bytes 6544090763171
proxy.node.origin_server_total_bytes 5724000323269
proxy.node.user_agent_total_bytes_avg_10s 6282149.000000
proxy.node.origin_server_total_bytes_avg_10s 4753366.000000
proxy.node.user_agent_xacts_per_second 7.497867
proxy.node.user_agents_total_documents_served 88198085
proxy.node.log.event_log_error_ok 0
proxy.node.log.event_log_error_skip 0
proxy.node.log.event_log_error_aggr 0
proxy.node.log.event_log_error_full 0
proxy.node.log.event_log_error_fail 0
proxy.node.log.event_log_access_ok 86256126
proxy.node.log.event_log_access_skip 0
proxy.node.log.event_log_access_aggr 0
proxy.node.log.event_log_access_full 0
proxy.node.log.event_log_access_fail 0
proxy.node.log.num_sent_to_network 0
proxy.node.log.num_lost_before_sent_to_network 0
proxy.node.log.num_received_from_network 0
proxy.node.log.num_flush_to_disk 0
proxy.node.log.num_lost_before_flush_to_disk 0
proxy.node.log.bytes_lost_before_preproc 0
proxy.node.log.bytes_sent_to_network 0
proxy.node.log.bytes_lost_before_sent_to_network 0
proxy.node.log.bytes_sent_to_network_avg_10s 0
proxy.node.log.bytes_received_from_network 0
proxy.node.log.bytes_received_from_network_avg_10s 0
proxy.node.log.bytes_flush_to_disk 0
proxy.node.log.bytes_lost_before_flush_to_disk 0
proxy.node.log.bytes_written_to_disk 0
proxy.node.log.bytes_lost_before_written_to_disk 0
proxy.process.http.completed_requests 86146921
proxy.process.http.total_incoming_connections 88198148
proxy.process.http.total_client_connections 88198148
proxy.process.http.total_client_connections_ipv4 88198148
proxy.process.http.total_client_connections_ipv6 0
proxy.process.http.total_server_connections 71804432
proxy.process.http.total_parent_proxy_connections 0
proxy.process.http.avg_transactions_per_client_connection 1.000000
proxy.process.http.avg_transactions_per_server_connection 1.146404
proxy.process.http.avg_transactions_per_parent_connection 0.000000
proxy.process.http.client_connection_time 0
proxy.process.http.parent_proxy_connection_time 0
proxy.process.http.server_connection_time 0
proxy.process.http.cache_connection_time 0
proxy.process.http.transaction_counts.errors.pre_accept_hangups 0
proxy.process.http.transaction_totaltime.errors.pre_accept_hangups 0.000000
proxy.process.http.transaction_counts.errors.empty_hangups 0
proxy.process.http.transaction_totaltime.errors.empty_hangups 0.000000
proxy.process.http.transaction_counts.errors.early_hangups 0
proxy.process.http.transaction_totaltime.errors.early_hangups 0.000000
proxy.process.http.incoming_requests 88198151
proxy.process.http.outgoing_requests 86509774
proxy.process.http.incoming_responses 82317015
proxy.process.http.invalid_client_requests 5462
proxy.process.http.missing_host_hdr 4500001
proxy.process.http.get_requests 83692630
proxy.process.http.head_requests 16
proxy.process.http.trace_requests 0
proxy.process.http.options_requests 0
proxy.process.http.post_requests 0
proxy.process.http.put_requests 0
proxy.process.http.push_requests 0
proxy.process.http.delete_requests 0
proxy.process.http.purge_requests 0
proxy.process.http.connect_requests 4500043
proxy.process.http.extension_method_requests 0
proxy.process.http.client_no_cache_requests 0
proxy.process.http.broken_server_connections 38491
proxy.process.http.cache_lookups 81612617
proxy.process.http.cache_writes 1420773
proxy.process.http.cache_updates 13743183
proxy.process.http.cache_deletes 197258
proxy.process.http.tunnels 4528842
proxy.process.http.throttled_proxy_only 0
proxy.process.http.icp_suggested_lookups 0
proxy.process.http.client_transaction_time 0
proxy.process.http.client_write_time 0
proxy.process.http.server_read_time 0
proxy.process.http.icp_transaction_time 0
proxy.process.http.icp_raw_transaction_time 0
proxy.process.http.parent_proxy_transaction_time 0
proxy.process.http.parent_proxy_raw_transaction_time 0
proxy.process.http.server_transaction_time 0
proxy.process.http.server_raw_transaction_time 0
proxy.process.http.user_agent_request_header_total_size 17466344160
proxy.process.http.user_agent_response_header_total_size 33522081785
proxy.process.http.user_agent_request_document_total_size 685806307
proxy.process.http.user_agent_response_document_total_size 6492424696608
proxy.process.http.origin_server_request_header_total_size 21298122389
proxy.process.http.origin_server_response_header_total_size 31072345504
proxy.process.http.origin_server_request_document_total_size 0
proxy.process.http.origin_server_response_document_total_size 5671637626134
proxy.process.http.parent_proxy_request_total_bytes 0
proxy.process.http.parent_proxy_response_total_bytes 0
proxy.process.http.pushed_response_header_total_size 0
proxy.process.http.pushed_document_total_size 0
proxy.process.http.response_document_size_100 3064727
proxy.process.http.response_document_size_1K 9457665
proxy.process.http.response_document_size_3K 1437848
proxy.process.http.response_document_size_5K 2147243
proxy.process.http.response_document_size_10K 5368623
proxy.process.http.response_document_size_1M 64621094
proxy.process.http.response_document_size_inf 49721
proxy.process.http.request_document_size_100 85072848
proxy.process.http.request_document_size_1K 1072065
proxy.process.http.request_document_size_3K 2008
proxy.process.http.request_document_size_5K 0
proxy.process.http.request_document_size_10K 0
proxy.process.http.request_document_size_1M 0
proxy.process.http.request_document_size_inf 0
proxy.process.http.user_agent_speed_bytes_per_sec_100 12737091
proxy.process.http.user_agent_speed_bytes_per_sec_1K 4422
proxy.process.http.user_agent_speed_bytes_per_sec_10K 74228
proxy.process.http.user_agent_speed_bytes_per_sec_100K 2095125
proxy.process.http.user_agent_speed_bytes_per_sec_1M 14466881
proxy.process.http.user_agent_speed_bytes_per_sec_10M 40775796
proxy.process.http.user_agent_speed_bytes_per_sec_100M 10209495
proxy.process.http.origin_server_speed_bytes_per_sec_100 2612
proxy.process.http.origin_server_speed_bytes_per_sec_1K 4051
proxy.process.http.origin_server_speed_bytes_per_sec_10K 76656
proxy.process.http.origin_server_speed_bytes_per_sec_100K 2099492
proxy.process.http.origin_server_speed_bytes_per_sec_1M 14356763
proxy.process.http.origin_server_speed_bytes_per_sec_10M 39004889
proxy.process.http.origin_server_speed_bytes_per_sec_100M 7752539
proxy.process.http.total_transactions_time 44629071611255685
proxy.process.http.total_transactions_think_time 0
proxy.process.http.cache_hit_fresh 1615985
proxy.process.http.cache_hit_mem_fresh 0
proxy.process.http.cache_hit_revalidated 4949005
proxy.process.http.cache_hit_ims 0
proxy.process.http.cache_hit_stale_served 617
proxy.process.http.cache_miss_cold 66028618
proxy.process.http.cache_miss_changed 8991320
proxy.process.http.cache_miss_client_no_cache 0
proxy.process.http.cache_miss_client_not_cacheable 4524380
proxy.process.http.cache_miss_ims 0
proxy.process.http.cache_read_error 62
proxy.process.http.tcp_hit_count_stat 1615985
proxy.process.http.tcp_hit_user_agent_bytes_stat 40905528880
proxy.process.http.tcp_hit_origin_server_bytes_stat 0
proxy.process.http.tcp_miss_count_stat 70456261
proxy.process.http.tcp_miss_user_agent_bytes_stat 5671556377795
proxy.process.http.tcp_miss_origin_server_bytes_stat 5466216840682
proxy.process.http.tcp_expired_miss_count_stat 0
proxy.process.http.tcp_expired_miss_user_agent_bytes_stat 0
proxy.process.http.tcp_expired_miss_origin_server_bytes_stat 0
proxy.process.http.tcp_refresh_hit_count_stat 4949005
proxy.process.http.tcp_refresh_hit_user_agent_bytes_stat 307265827073
proxy.process.http.tcp_refresh_hit_origin_server_bytes_stat 2687313448
proxy.process.http.tcp_refresh_miss_count_stat 8991320
proxy.process.http.tcp_refresh_miss_user_agent_bytes_stat 518936292282
proxy.process.http.tcp_refresh_miss_origin_server_bytes_stat 519393655521
proxy.process.http.tcp_client_refresh_count_stat 0
proxy.process.http.tcp_client_refresh_user_agent_bytes_stat 0
proxy.process.http.tcp_client_refresh_origin_server_bytes_stat 0
proxy.process.http.tcp_ims_hit_count_stat 0
proxy.process.http.tcp_ims_hit_user_agent_bytes_stat 0
proxy.process.http.tcp_ims_hit_origin_server_bytes_stat 0
proxy.process.http.tcp_ims_miss_count_stat 0
proxy.process.http.tcp_ims_miss_user_agent_bytes_stat 0
proxy.process.http.tcp_ims_miss_origin_server_bytes_stat 0
proxy.process.http.err_client_abort_count_stat 17600
proxy.process.http.err_client_abort_user_agent_bytes_stat 5207533065
proxy.process.http.err_client_abort_origin_server_bytes_stat 5026460949
proxy.process.http.err_connect_fail_count_stat 96737
proxy.process.http.err_connect_fail_user_agent_bytes_stat 72866869
proxy.process.http.err_connect_fail_origin_server_bytes_stat 7989457
proxy.process.http.misc_count_stat 20013
proxy.process.http.misc_user_agent_bytes_stat 154502896
proxy.process.http.background_fill_bytes_aborted_stat 0
proxy.process.http.background_fill_bytes_completed_stat 0
proxy.process.http.cache_write_errors 0
proxy.process.http.cache_read_errors 62
proxy.process.http.100_responses 0
proxy.process.http.101_responses 0
proxy.process.http.1xx_responses 70
proxy.process.http.200_responses 70626071
proxy.process.http.201_responses 0
proxy.process.http.202_responses 1
proxy.process.http.203_responses 10
proxy.process.http.204_responses 17642
proxy.process.http.205_responses 0
proxy.process.http.206_responses 0
proxy.process.http.2xx_responses 70643724
proxy.process.http.300_responses 0
proxy.process.http.301_responses 3970579
proxy.process.http.302_responses 6300928
proxy.process.http.303_responses 33474
proxy.process.http.304_responses 591
proxy.process.http.305_responses 0
proxy.process.http.307_responses 17149
proxy.process.http.3xx_responses 10322721
proxy.process.http.400_responses 3687
proxy.process.http.401_responses 2617
proxy.process.http.402_responses 673
proxy.process.http.403_responses 52996
proxy.process.http.404_responses 415752
proxy.process.http.405_responses 78
proxy.process.http.406_responses 1
proxy.process.http.407_responses 0
proxy.process.http.408_responses 20
proxy.process.http.409_responses 12
proxy.process.http.410_responses 23796
proxy.process.http.411_responses 0
proxy.process.http.412_responses 0
proxy.process.http.413_responses 0
proxy.process.http.414_responses 0
proxy.process.http.415_responses 0
proxy.process.http.416_responses 0
proxy.process.http.4xx_responses 499852
proxy.process.http.500_responses 17448
proxy.process.http.501_responses 12
proxy.process.http.502_responses 123057
proxy.process.http.503_responses 16012
proxy.process.http.504_responses 6937
proxy.process.http.505_responses 0
proxy.process.http.5xx_responses 164237
proxy.process.http.transaction_counts.hit_fresh 1616664
proxy.process.http.transaction_totaltime.hit_fresh 121742.570312
proxy.process.http.transaction_counts.hit_fresh.process 1616664
proxy.process.http.transaction_totaltime.hit_fresh.process 121742.453125
proxy.process.http.transaction_counts.hit_revalidated 4949005
proxy.process.http.transaction_totaltime.hit_revalidated 659668.250000
proxy.process.http.transaction_counts.miss_cold 65931881
proxy.process.http.transaction_totaltime.miss_cold 25020654.000000
proxy.process.http.transaction_counts.miss_not_cacheable 4524380
proxy.process.http.transaction_totaltime.miss_not_cacheable 4129507.000000
proxy.process.http.transaction_counts.miss_changed 8991320
proxy.process.http.transaction_totaltime.miss_changed 4268950.000000
proxy.process.http.transaction_counts.miss_client_no_cache 0
proxy.process.http.transaction_totaltime.miss_client_no_cache 0.000000
proxy.process.http.transaction_counts.errors.aborts 17613
proxy.process.http.transaction_totaltime.errors.aborts 4228755.000000
proxy.process.http.transaction_counts.errors.possible_aborts 0
proxy.process.http.transaction_totaltime.errors.possible_aborts 0.000000
proxy.process.http.transaction_counts.errors.connect_failed 96737
proxy.process.http.transaction_totaltime.errors.connect_failed 4738861.500000
proxy.process.http.transaction_counts.errors.other 16265
proxy.process.http.transaction_totaltime.errors.other 1379263.875000
proxy.process.http.transaction_counts.other.unclassified 3056
proxy.process.http.transaction_totaltime.other.unclassified 38646.671875
proxy.process.http.total_x_redirect_count 0
proxy.process.https.incoming_requests 0
proxy.process.https.total_client_connections 0
proxy.process.net.net_handler_run 4483312742
proxy.process.net.read_bytes 6202110190160
proxy.process.net.write_bytes 6554422599826
proxy.process.net.calls_to_readfromnet 0
proxy.process.net.calls_to_readfromnet_afterpoll 0
proxy.process.net.calls_to_read 0
proxy.process.net.calls_to_read_nodata 0
proxy.process.net.calls_to_writetonet 0
proxy.process.net.calls_to_writetonet_afterpoll 0
proxy.process.net.calls_to_write 0
proxy.process.net.calls_to_write_nodata 0
proxy.process.socks.connections_successful 0
proxy.process.socks.connections_unsuccessful 0
proxy.process.net.inactivity_cop_lock_acquire_failure 0
proxy.process.cache.read_per_sec 0.000000
proxy.process.cache.write_per_sec 0.000000
proxy.process.cache.KB_read_per_sec 0.000000
proxy.process.cache.KB_write_per_sec 0.000000
proxy.process.hostdb.total_entries 135000
proxy.process.hostdb.total_lookups 86545196
proxy.process.hostdb.ttl 0.000000
proxy.process.hostdb.ttl_expires 93380529
proxy.process.hostdb.re_dns_on_reload 0
proxy.process.hostdb.bytes 25935872
proxy.process.dns.total_dns_lookups 1175436102
proxy.process.dns.lookup_avg_time 0
proxy.process.dns.lookup_successes 54137690
proxy.process.dns.fail_avg_time 0
proxy.process.dns.lookup_failures 330899
proxy.process.dns.retries 81645
proxy.process.dns.max_retries_exceeded 12270
proxy.process.log.event_log_error_ok 123159
proxy.process.log.event_log_error_skip 0
proxy.process.log.event_log_error_aggr 0
proxy.process.log.event_log_error_full 0
proxy.process.log.event_log_error_fail 0
proxy.process.log.event_log_access_ok 86256191
proxy.process.log.event_log_access_skip 0
proxy.process.log.event_log_access_aggr 0
proxy.process.log.event_log_access_full 0
proxy.process.log.event_log_access_fail 0
proxy.process.log.num_sent_to_network 0
proxy.process.log.num_lost_before_sent_to_network 0
proxy.process.log.num_received_from_network 0
proxy.process.log.num_flush_to_disk 86379324
proxy.process.log.num_lost_before_flush_to_disk 0
proxy.process.log.bytes_lost_before_preproc 0
proxy.process.log.bytes_sent_to_network 0
proxy.process.log.bytes_lost_before_sent_to_network 0
proxy.process.log.bytes_received_from_network 0
proxy.process.log.bytes_flush_to_disk 12351274552
proxy.process.log.bytes_lost_before_flush_to_disk 0
proxy.process.log.bytes_written_to_disk 12351274552
proxy.process.log.bytes_lost_before_written_to_disk 0
proxy.process.http.background_fill_current_count 0
proxy.process.http.current_client_connections 3
proxy.process.http.current_active_client_connections 3
proxy.process.http.websocket.current_active_client_connections 0
proxy.process.http.current_client_transactions 3
proxy.process.http.current_parent_proxy_transactions 0
proxy.process.http.current_icp_transactions 0
proxy.process.http.current_server_transactions 2
proxy.process.http.current_parent_proxy_raw_transactions 0
proxy.process.http.current_icp_raw_transactions 0
proxy.process.http.current_server_raw_transactions 0
proxy.process.http.current_parent_proxy_connections 0
proxy.process.http.current_server_connections 89
proxy.process.http.current_cache_connections 3
proxy.process.net.connections_currently_open 93
proxy.process.net.accepts_currently_open 2
proxy.process.socks.connections_currently_open 0
proxy.process.cache.bytes_used 5353586688
proxy.process.cache.bytes_total 5361975296
proxy.process.cache.ram_cache.total_bytes 6717440
proxy.process.cache.ram_cache.bytes_used 66271232
proxy.process.cache.ram_cache.hits 2122644
proxy.process.cache.ram_cache.misses 31937201
proxy.process.cache.pread_count 0
proxy.process.cache.percent_full 99
proxy.process.cache.lookup.active 0
proxy.process.cache.lookup.success 0
proxy.process.cache.lookup.failure 0
proxy.process.cache.read.active 1
proxy.process.cache.read.success 15330728
proxy.process.cache.read.failure 64999201
proxy.process.cache.write.active 1
proxy.process.cache.write.success 1071211
proxy.process.cache.write.failure 8218
proxy.process.cache.write.backlog.failure 0
proxy.process.cache.update.active 1
proxy.process.cache.update.success 13070053
proxy.process.cache.update.failure 1162
proxy.process.cache.remove.active 0
proxy.process.cache.remove.success 0
proxy.process.cache.remove.failure 0
proxy.process.cache.evacuate.active 0
proxy.process.cache.evacuate.success 0
proxy.process.cache.evacuate.failure 0
proxy.process.cache.scan.active 0
proxy.process.cache.scan.success 0
proxy.process.cache.scan.failure 0
proxy.process.cache.direntries.total 669416
proxy.process.cache.direntries.used 23940
proxy.process.cache.directory_collision 10446
proxy.process.cache.frags_per_doc.1 9001220
proxy.process.cache.frags_per_doc.2 0
proxy.process.cache.frags_per_doc.3+ 5051
proxy.process.cache.read_busy.success 47
proxy.process.cache.read_busy.failure 1814
proxy.process.cache.write_bytes_stat 0
proxy.process.cache.vector_marshals 14799315
proxy.process.cache.hdr_marshals 17074486
proxy.process.cache.hdr_marshal_bytes 47474020512
proxy.process.cache.gc_bytes_evacuated 0
proxy.process.cache.gc_frags_evacuated 0
proxy.process.hostdb.total_hits 38811514
proxy.process.dns.success_avg_time 0
proxy.process.dns.in_flight 0
proxy.process.congestion.congested_on_conn_failures 0
proxy.process.congestion.congested_on_max_connection 0
proxy.process.cluster.connections_open 0
proxy.process.cluster.connections_opened 0
proxy.process.cluster.connections_closed 0
proxy.process.cluster.slow_ctrl_msgs_sent 0
proxy.process.cluster.connections_read_locked 0
proxy.process.cluster.connections_write_locked 0
proxy.process.cluster.reads 0
proxy.process.cluster.read_bytes 0
proxy.process.cluster.writes 0
proxy.process.cluster.write_bytes 0
proxy.process.cluster.control_messages_sent 0
proxy.process.cluster.control_messages_received 0
proxy.process.cluster.op_delayed_for_lock 0
proxy.process.cluster.connections_bumped 0
proxy.process.cluster.net_backup 0
proxy.process.cluster.nodes 1
proxy.process.cluster.machines_allocated 1
proxy.process.cluster.machines_freed 0
proxy.process.cluster.configuration_changes 0
proxy.process.cluster.delayed_reads 0
proxy.process.cluster.byte_bank_used 0
proxy.process.cluster.alloc_data_news 0
proxy.process.cluster.write_bb_mallocs 0
proxy.process.cluster.partial_reads 0
proxy.process.cluster.partial_writes 0
proxy.process.cluster.cache_outstanding 0
proxy.process.cluster.remote_op_timeouts 0
proxy.process.cluster.remote_op_reply_timeouts 0
proxy.process.cluster.chan_inuse 0
proxy.process.cluster.open_delays 0
proxy.process.cluster.connections_avg_time 0.000000
proxy.process.cluster.control_messages_avg_send_time 0.000000
proxy.process.cluster.control_messages_avg_receive_time 0.000000
proxy.process.cluster.open_delay_time 0.000000
proxy.process.cluster.cache_callback_time 0.000000
proxy.process.cluster.rmt_cache_callback_time 0.000000
proxy.process.cluster.lkrmt_cache_callback_time 0.000000
proxy.process.cluster.local_connection_time 0.000000
proxy.process.cluster.remote_connection_time 0.000000
proxy.process.cluster.rdmsg_assemble_time 0.000000
proxy.process.cluster.cluster_ping_time 0.000000
proxy.process.cluster.cache_callbacks 0
proxy.process.cluster.rmt_cache_callbacks 0
proxy.process.cluster.lkrmt_cache_callbacks 0
proxy.process.cluster.local_connections_closed 0
proxy.process.cluster.remote_connections_closed 0
proxy.process.cluster.setdata_no_clustervc 0
proxy.process.cluster.setdata_no_tunnel 0
proxy.process.cluster.setdata_no_cachevc 0
proxy.process.cluster.setdata_no_cluster 0
proxy.process.cluster.vc_write_stall 0
proxy.process.cluster.no_remote_space 0
proxy.process.cluster.level1_bank 0
proxy.process.cluster.multilevel_bank 0
proxy.process.cluster.vc_cache_insert_lock_misses 0
proxy.process.cluster.vc_cache_inserts 0
proxy.process.cluster.vc_cache_lookup_lock_misses 0
proxy.process.cluster.vc_cache_lookup_hits 0
proxy.process.cluster.vc_cache_lookup_misses 0
proxy.process.cluster.vc_cache_scans 488188928
proxy.process.cluster.vc_cache_scan_lock_misses 0
proxy.process.cluster.vc_cache_purges 0
proxy.process.cluster.write_lock_misses 0
proxy.process.cluster.vc_read_list_len 0
proxy.process.cluster.vc_write_list_len 0
proxy.process.log.log_files_open 2
proxy.process.log.log_files_space_used 5426491463
proxy.process.update.successes 0
proxy.process.update.no_actions 0
proxy.process.update.fails 0
proxy.process.update.unknown_status 0
proxy.process.update.state_machines 0
proxy.process.cache.volume_0.bytes_used 5353586688
proxy.process.cache.volume_0.bytes_total 5361975296
proxy.process.cache.volume_0.ram_cache.total_bytes 6717440
proxy.process.cache.volume_0.ram_cache.bytes_used 66271232
proxy.process.cache.volume_0.ram_cache.hits 2122644
proxy.process.cache.volume_0.ram_cache.misses 31937201
proxy.process.cache.volume_0.pread_count 0
proxy.process.cache.volume_0.percent_full 99
proxy.process.cache.volume_0.lookup.active 0
proxy.process.cache.volume_0.lookup.success 0
proxy.process.cache.volume_0.lookup.failure 0
proxy.process.cache.volume_0.read.active 1
proxy.process.cache.volume_0.read.success 15330728
proxy.process.cache.volume_0.read.failure 64999201
proxy.process.cache.volume_0.write.active 1
proxy.process.cache.volume_0.write.success 1071211
proxy.process.cache.volume_0.write.failure 8218
proxy.process.cache.volume_0.write.backlog.failure 0
proxy.process.cache.volume_0.update.active 1
proxy.process.cache.volume_0.update.success 13070053
proxy.process.cache.volume_0.update.failure 1162
proxy.process.cache.volume_0.remove.active 0
proxy.process.cache.volume_0.remove.success 0
proxy.process.cache.volume_0.remove.failure 0
proxy.process.cache.volume_0.evacuate.active 0
proxy.process.cache.volume_0.evacuate.success 0
proxy.process.cache.volume_0.evacuate.failure 0
proxy.process.cache.volume_0.scan.active 0
proxy.process.cache.volume_0.scan.success 0
proxy.process.cache.volume_0.scan.failure 0
proxy.process.cache.volume_0.direntries.total 669416
proxy.process.cache.volume_0.direntries.used 23940
proxy.process.cache.volume_0.directory_collision 10446
proxy.process.cache.volume_0.frags_per_doc.1 9001220
proxy.process.cache.volume_0.frags_per_doc.2 0
proxy.process.cache.volume_0.frags_per_doc.3+ 5051
proxy.process.cache.volume_0.read_busy.success 4758917
proxy.process.cache.volume_0.read_busy.failure 1814
proxy.process.cache.volume_0.write_bytes_stat 0
proxy.process.cache.volume_0.vector_marshals 0
proxy.process.cache.volume_0.hdr_marshals 0
proxy.process.cache.volume_0.hdr_marshal_bytes 0
proxy.process.cache.volume_0.gc_bytes_evacuated 0
proxy.process.cache.volume_0.gc_frags_evacuated 0
`
